### ISSUE TITLE
Why is this not zip-safe

### ISSUE THREAD

**Issue by hellerbarde** [wenLiangcan/pip2pkgbuild#1]
Why did you declare your package as not-zip-safe?

cheers
hellerbarde

**Comment by wenLiangcan** [comment]
Thanks for pointing it out. I just did "copy & paste" from a Python packaging tutorial and known nothing about it.            
    
Now I read the documentation and I think whether zip-safe or not is not a big issue for such a small project (it just a standalone script), so, I decided to simply omit it in next version.
