### ISSUE TITLE
Setuptools deprecating, using new python method for installing

### ISSUE THREAD

**Issue by Popolon** [wenLiangcan/pip2pkgbuild#16]
New makedepends (replace python-setuptools):

<pre>makedepends=('python-pip' 'python-wheel' 'python-flit' 'python-installer')</pre>

The new method is:
<pre>build() {
    cd "${srcdir}/${_module}-${pkgver}"
    python -m build --wheel --no-isolation
}

package() {
    depends+=()
    cd "${srcdir}/${_module}-${pkgver}"
    python -m installer --destdir="$pkgdir" dist/*.whl
}
</pre>

See this guideline:
https://wiki.archlinux.org/title/Python_package_guidelines#Installation_methods

**Comment by wenLiangcan** [comment]
Added as an optional feature, as there are not much modules support this standard.

**Comment by Popolon** [comment]
Thank you very much. Your package is really useful, I used it for serveral packages.
I need these changes for the [python-jupyterlite](https://aur.archlinux.org/packages/python-jupyterlite) package for information.
