### ISSUE TITLE
Add support for poetry packages.

### ISSUE THREAD

**Issue by Fom123** [wenLiangcan/pip2pkgbuild#19]
I attempted to use the tool to generate a `PKGBUILD` file for a Python package that uses [poetry](https://python-poetry.org/) for managing its dependencies, but the installation process failed with the following error message:

```bash
python: can't open file '/tmp/makepkg/name/src/name-0.1.0/setup.py': [Errno 2] No such file or directory
```

I believe this error is occurring because poetry uses `pyproject.toml` instead of `setup.py` to manage package metadata and dependencies. 

I would like to request the support for poetry packages. This would make the tool more versatile and useful for users who rely on poetry to manage dependencies for their Python packages.

Thank you for your attention to this matter, and please let me know if you require any further information from me.

**Comment by wenLiangcan** [comment]
I guess the one you are going to package is aligned with the `PEP517` standard and should be already supported by `pip2pkgbuild`, Could you try to generate the `PKGBUILD` by using the following command?
```shell 
pip2pkguild --pep517 <module name>
```

**Comment by Fom123** [comment]
> I guess the one you are going to package is aligned with the `PEP517` standard and should be already supported by `pip2pkgbuild`, Could you try to generate the `PKGBUILD` by using the following command?
> 
> ```shell
> pip2pkguild --pep517 <module name>
> ```

It works, thank you! Somehow didn't notice that option. I will close it as a duplicate of #16, then.
