### ISSUE TITLE
Setup.py is supposedly deprecated

### ISSUE THREAD

**Issue by mon0theist** [wenLiangcan/pip2pkgbuild#22]
I used this to generate PKGBUILDs for two python modules, cs50 and submit50. However upon installing the packages, I get the below terminal output:

![image](https://github.com/wenLiangcan/pip2pkgbuild/assets/12420010/ad22fc58-3ac0-41e0-853f-df5eaa713092)

The package installations still seemed to complete anyway, but I thought maybe I should post this here just in case.

**Comment by wenLiangcan** [comment]
Actually, `pip2pkgbuild` does support generation of `PEP517` (the `pypa/build`, `pypa/installer` staffs mentioned in your screenshot) based `PKGBUILD` by the `--pep517` option. But, it will only generate such `PKGBUILD` if there's a `pyproject.toml` file provided by the Python module, according to the [wiki](https://wiki.archlinux.org/title/Python_package_guidelines#Installation_methods).     
   
However, after I tried, it seems `pypa/build` and `pypa/installer` can even deal with modules without the `TOML` file. So, I will release a new version to remove the verification logic of the `--pep517` option.

**Comment by Popolon** [comment]
looks like 0.3.4 still try to use setup.py.

A solution could be this in PKGBUILD:

in build():

if [ -e setup.py ]; then
  python setup.py build
else
  python -m build --wheel --no-isolation
fi

and in package():
if [ -e setup.py ]; then
  python setup.py install --root="${pkgdir}" --optimize=1 --skip-build
else
  python -m installer --destdir="${pkgdir}" dist/*.whl
fi
