### ISSUE TITLE
Make PEP517+python 3 the default

### ISSUE THREAD

**Issue by hseg** [wenLiangcan/pip2pkgbuild#32]
While it's all well and good to provide tooling for the usecases wanting `python2` packages, most users are going to go for the default and not bother passing `--pep517`. Swapping these defaults would help here.

**Comment by RubenKelevra** [comment]
If you create a patch I'm happy to add it to the aur package :)

**Comment by hseg** [comment]
I don't know why I thought Python 2 was the default -- I think I misinterpreted the choice to make split packages by default. Opened a PR to fix this.

**Comment by hseg** [comment]
In case it takes a while for my PRs to be merged, I've created https://github.com/hseg/pip2pkgbuild/tree/wishlist containing all of my outstanding PRs (it will be deleted if they all get merged).
